/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cppmjni_HelloJNICpp */

#ifndef _Included_cppmjni_HelloJNICpp
#define _Included_cppmjni_HelloJNICpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cppmjni_HelloJNICpp
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cppmjni_HelloJNICpp_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
